templates:
  params:
    author-email: bdellaterra@voodooglobe.com
    author-name: Brian Dellaterra
    category: UNLICENSED
    copyright: Copyright held by Brian Dellaterra
    github-username: bdellaterra

